// DO NOT EDIT. generated by webtyp.com/ormc

package networkmanager

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type NetworkSetting struct {
	Id string
	TenantId string
	DhcpServer string
	DynamicPool string
	FilterDns string
	Unregistered string
	UpdatedAt int64
}

func (m *NetworkSetting) ModelName() string { return "network_setting" }

func (m *NetworkSetting) Schema() []model.Field { return NetworkSettingModel.Fields }

func (m *NetworkSetting) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.DhcpServer, &m.DynamicPool, &m.FilterDns, &m.Unregistered, &m.UpdatedAt} }

func (m *NetworkSetting) IsNil() bool { return m == nil }

func (m *NetworkSetting) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("dhcp_server", m.DhcpServer)
	if m.DynamicPool != "" { w.String("dynamic_pool", m.DynamicPool) }
	w.String("filter_dns", m.FilterDns)
	w.String("unregistered", m.Unregistered)
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *NetworkSetting) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("dhcp_server"); ok { m.DhcpServer = v }
	if v, ok := r.String("dynamic_pool"); ok { m.DynamicPool = v }
	if v, ok := r.String("filter_dns"); ok { m.FilterDns = v }
	if v, ok := r.String("unregistered"); ok { m.Unregistered = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type NetworkSettingList []*NetworkSetting

func (s *NetworkSettingList) Len() int             { return len(*s) }
func (s *NetworkSettingList) At(i int) model.Fielder { return (*s)[i] }
func (s *NetworkSettingList) Append() model.Fielder  { v := &NetworkSetting{}; *s = append(*s, v); return v }
func (s *NetworkSettingList) IsNil() bool          { return s == nil }
func (s *NetworkSettingList) EncodeFields(_ model.FieldWriter) {}
func (s *NetworkSettingList) DecodeFields(_ model.FieldReader) {}

func (m *NetworkSetting) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var NetworkSetting_ = struct {
	Id string
	TenantId string
	DhcpServer string
	DynamicPool string
	FilterDns string
	Unregistered string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	DhcpServer: "dhcp_server",
	DynamicPool: "dynamic_pool",
	FilterDns: "filter_dns",
	Unregistered: "unregistered",
	UpdatedAt: "updated_at",
}

func ReadOneNetworkSetting(qb *orm.QB, model *NetworkSetting) (*NetworkSetting, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllNetworkSetting(qb *orm.QB) (NetworkSettingList, error) {
	var results NetworkSettingList
	err := qb.ReadAll(
		func() model.Model { return &NetworkSetting{} },
		func(m model.Model) { results = append(results, m.(*NetworkSetting)) },
	)
	return results, err
}

type NetworkApply struct {
	Id string
	TenantId string
	Fingerprint string
	Changes int64
	AppliedAt int64
}

func (m *NetworkApply) ModelName() string { return "network_apply" }

func (m *NetworkApply) Schema() []model.Field { return NetworkApplyModel.Fields }

func (m *NetworkApply) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.Fingerprint, &m.Changes, &m.AppliedAt} }

func (m *NetworkApply) IsNil() bool { return m == nil }

func (m *NetworkApply) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("fingerprint", m.Fingerprint)
	w.Int("changes", m.Changes)
	w.Int("applied_at", m.AppliedAt)
}

func (m *NetworkApply) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("fingerprint"); ok { m.Fingerprint = v }
	if v, ok := r.Int("changes"); ok { m.Changes = v }
	if v, ok := r.Int("applied_at"); ok { m.AppliedAt = v }
}

type NetworkApplyList []*NetworkApply

func (s *NetworkApplyList) Len() int             { return len(*s) }
func (s *NetworkApplyList) At(i int) model.Fielder { return (*s)[i] }
func (s *NetworkApplyList) Append() model.Fielder  { v := &NetworkApply{}; *s = append(*s, v); return v }
func (s *NetworkApplyList) IsNil() bool          { return s == nil }
func (s *NetworkApplyList) EncodeFields(_ model.FieldWriter) {}
func (s *NetworkApplyList) DecodeFields(_ model.FieldReader) {}

func (m *NetworkApply) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var NetworkApply_ = struct {
	Id string
	TenantId string
	Fingerprint string
	Changes string
	AppliedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	Fingerprint: "fingerprint",
	Changes: "changes",
	AppliedAt: "applied_at",
}

func ReadOneNetworkApply(qb *orm.QB, model *NetworkApply) (*NetworkApply, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllNetworkApply(qb *orm.QB) (NetworkApplyList, error) {
	var results NetworkApplyList
	err := qb.ReadAll(
		func() model.Model { return &NetworkApply{} },
		func(m model.Model) { results = append(results, m.(*NetworkApply)) },
	)
	return results, err
}

type PlanItem struct {
	Id string
	Category string
	Kind string
	Object string
	Name string
	Mac string
	Before string
	After string
	Reason string
	Online bool
	Fingerprint string
}

func (m *PlanItem) ModelName() string { return "plan_item" }

func (m *PlanItem) Schema() []model.Field { return PlanItemModel.Fields }

func (m *PlanItem) Pointers() []any { return []any{&m.Id, &m.Category, &m.Kind, &m.Object, &m.Name, &m.Mac, &m.Before, &m.After, &m.Reason, &m.Online, &m.Fingerprint} }

func (m *PlanItem) IsNil() bool { return m == nil }

func (m *PlanItem) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("category", m.Category)
	w.String("kind", m.Kind)
	w.String("object", m.Object)
	w.String("name", m.Name)
	w.String("mac", m.Mac)
	w.String("before", m.Before)
	w.String("after", m.After)
	w.String("reason", m.Reason)
	w.Bool("online", m.Online)
	w.String("fingerprint", m.Fingerprint)
}

func (m *PlanItem) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("category"); ok { m.Category = v }
	if v, ok := r.String("kind"); ok { m.Kind = v }
	if v, ok := r.String("object"); ok { m.Object = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("mac"); ok { m.Mac = v }
	if v, ok := r.String("before"); ok { m.Before = v }
	if v, ok := r.String("after"); ok { m.After = v }
	if v, ok := r.String("reason"); ok { m.Reason = v }
	if v, ok := r.Bool("online"); ok { m.Online = v }
	if v, ok := r.String("fingerprint"); ok { m.Fingerprint = v }
}

type PlanItemList []*PlanItem

func (s *PlanItemList) Len() int             { return len(*s) }
func (s *PlanItemList) At(i int) model.Fielder { return (*s)[i] }
func (s *PlanItemList) Append() model.Fielder  { v := &PlanItem{}; *s = append(*s, v); return v }
func (s *PlanItemList) IsNil() bool          { return s == nil }
func (s *PlanItemList) EncodeFields(_ model.FieldWriter) {}
func (s *PlanItemList) DecodeFields(_ model.FieldReader) {}

func (m *PlanItem) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ConnectionRow struct {
	Mac string
	Ip string
	HostName string
	Source string
	Registered bool
	Name string
}

func (m *ConnectionRow) ModelName() string { return "connection_row" }

func (m *ConnectionRow) Schema() []model.Field { return ConnectionRowModel.Fields }

func (m *ConnectionRow) Pointers() []any { return []any{&m.Mac, &m.Ip, &m.HostName, &m.Source, &m.Registered, &m.Name} }

func (m *ConnectionRow) IsNil() bool { return m == nil }

func (m *ConnectionRow) EncodeFields(w model.FieldWriter) {
	w.String("mac", m.Mac)
	w.String("ip", m.Ip)
	w.String("host_name", m.HostName)
	w.String("source", m.Source)
	w.Bool("registered", m.Registered)
	w.String("name", m.Name)
}

func (m *ConnectionRow) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("mac"); ok { m.Mac = v }
	if v, ok := r.String("ip"); ok { m.Ip = v }
	if v, ok := r.String("host_name"); ok { m.HostName = v }
	if v, ok := r.String("source"); ok { m.Source = v }
	if v, ok := r.Bool("registered"); ok { m.Registered = v }
	if v, ok := r.String("name"); ok { m.Name = v }
}

type ConnectionRowList []*ConnectionRow

func (s *ConnectionRowList) Len() int             { return len(*s) }
func (s *ConnectionRowList) At(i int) model.Fielder { return (*s)[i] }
func (s *ConnectionRowList) Append() model.Fielder  { v := &ConnectionRow{}; *s = append(*s, v); return v }
func (s *ConnectionRowList) IsNil() bool          { return s == nil }
func (s *ConnectionRowList) EncodeFields(_ model.FieldWriter) {}
func (s *ConnectionRowList) DecodeFields(_ model.FieldReader) {}

func (m *ConnectionRow) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DiscoveredRow struct {
	Mac string
	Ip string
	Name string
	Internet bool
}

func (m *DiscoveredRow) ModelName() string { return "discovered_row" }

func (m *DiscoveredRow) Schema() []model.Field { return DiscoveredRowModel.Fields }

func (m *DiscoveredRow) Pointers() []any { return []any{&m.Mac, &m.Ip, &m.Name, &m.Internet} }

func (m *DiscoveredRow) IsNil() bool { return m == nil }

func (m *DiscoveredRow) EncodeFields(w model.FieldWriter) {
	w.String("mac", m.Mac)
	w.String("ip", m.Ip)
	w.String("name", m.Name)
	w.Bool("internet", m.Internet)
}

func (m *DiscoveredRow) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("mac"); ok { m.Mac = v }
	if v, ok := r.String("ip"); ok { m.Ip = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.Bool("internet"); ok { m.Internet = v }
}

type DiscoveredRowList []*DiscoveredRow

func (s *DiscoveredRowList) Len() int             { return len(*s) }
func (s *DiscoveredRowList) At(i int) model.Fielder { return (*s)[i] }
func (s *DiscoveredRowList) Append() model.Fielder  { v := &DiscoveredRow{}; *s = append(*s, v); return v }
func (s *DiscoveredRowList) IsNil() bool          { return s == nil }
func (s *DiscoveredRowList) EncodeFields(_ model.FieldWriter) {}
func (s *DiscoveredRowList) DecodeFields(_ model.FieldReader) {}

func (m *DiscoveredRow) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ImportReport struct {
	Created int64
	Skipped int64
}

func (m *ImportReport) ModelName() string { return "import_report" }

func (m *ImportReport) Schema() []model.Field { return ImportReportModel.Fields }

func (m *ImportReport) Pointers() []any { return []any{&m.Created, &m.Skipped} }

func (m *ImportReport) IsNil() bool { return m == nil }

func (m *ImportReport) EncodeFields(w model.FieldWriter) {
	w.Int("created", m.Created)
	w.Int("skipped", m.Skipped)
}

func (m *ImportReport) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("created"); ok { m.Created = v }
	if v, ok := r.Int("skipped"); ok { m.Skipped = v }
}

type ImportReportList []*ImportReport

func (s *ImportReportList) Len() int             { return len(*s) }
func (s *ImportReportList) At(i int) model.Fielder { return (*s)[i] }
func (s *ImportReportList) Append() model.Fielder  { v := &ImportReport{}; *s = append(*s, v); return v }
func (s *ImportReportList) IsNil() bool          { return s == nil }
func (s *ImportReportList) EncodeFields(_ model.FieldWriter) {}
func (s *ImportReportList) DecodeFields(_ model.FieldReader) {}

func (m *ImportReport) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ApplyNetworkArgs struct {
	Fingerprint string
}

func (m *ApplyNetworkArgs) ModelName() string { return "apply_network_args" }

func (m *ApplyNetworkArgs) Schema() []model.Field { return ApplyNetworkArgsModel.Fields }

func (m *ApplyNetworkArgs) Pointers() []any { return []any{&m.Fingerprint} }

func (m *ApplyNetworkArgs) IsNil() bool { return m == nil }

func (m *ApplyNetworkArgs) EncodeFields(w model.FieldWriter) {
	w.String("fingerprint", m.Fingerprint)
}

func (m *ApplyNetworkArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("fingerprint"); ok { m.Fingerprint = v }
}

type ApplyNetworkArgsList []*ApplyNetworkArgs

func (s *ApplyNetworkArgsList) Len() int             { return len(*s) }
func (s *ApplyNetworkArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ApplyNetworkArgsList) Append() model.Fielder  { v := &ApplyNetworkArgs{}; *s = append(*s, v); return v }
func (s *ApplyNetworkArgsList) IsNil() bool          { return s == nil }
func (s *ApplyNetworkArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ApplyNetworkArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ApplyNetworkArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

